### PR TITLE
Implement RowSplitsToRowIds with cub device scan.

### PR DESCRIPTION
**Pull request by csukuangfj**
Repost the result before the change from #484 

```
op_name,dtype,device,problem_size,number_of_iterations,elapsed_us_per_iteration
ExclusiveSum,int32,kCpu,100,500,0.430107
ExclusiveSum,int32,kCpu,500,500,0.652313
ExclusiveSum,int32,kCpu,1000,500,0.862122
ExclusiveSum,int32,kCpu,2000,500,1.428127
ExclusiveSum,int32,kCpu,5000,200,2.830029
ExclusiveSum,int32,kCpu,10000,100,5.679131
ExclusiveSum,int32,kCpu,100000,10,57.196617
ExclusiveSum,int32,kCuda,100,500,15.522688
ExclusiveSum,int32,kCuda,500,500,13.503168
ExclusiveSum,int32,kCuda,1000,500,12.769920
ExclusiveSum,int32,kCuda,2000,500,12.796735
ExclusiveSum,int32,kCuda,5000,200,13.019680
ExclusiveSum,int32,kCuda,10000,100,10.883519
ExclusiveSum,int32,kCuda,100000,10,13.872001
RowSplitsToRowIds,int32,kCpu,100,500,6.326199
RowSplitsToRowIds,int32,kCpu,500,500,39.864063
RowSplitsToRowIds,int32,kCpu,1000,500,107.650284
RowSplitsToRowIds,int32,kCpu,2000,500,185.015686
RowSplitsToRowIds,int32,kCpu,5000,200,536.605164
RowSplitsToRowIds,int32,kCpu,10000,100,1650.300049
RowSplitsToRowIds,int32,kCpu,100000,10,51252.414062
RowSplitsToRowIds,int32,kCuda,100,500,27.510401
RowSplitsToRowIds,int32,kCuda,500,500,47.054462
RowSplitsToRowIds,int32,kCuda,1000,500,121.602242
RowSplitsToRowIds,int32,kCuda,2000,500,115.474808
RowSplitsToRowIds,int32,kCuda,5000,200,240.739502
RowSplitsToRowIds,int32,kCuda,10000,100,453.319977
RowSplitsToRowIds,int32,kCuda,100000,10,4515.548828
```

---

The result of this pullrequest is (which is **FASTER** than before):

```
ExclusiveSum,int32,kCpu,100,500,0.388145
ExclusiveSum,int32,kCpu,500,500,0.594139
ExclusiveSum,int32,kCpu,1000,500,0.837803
ExclusiveSum,int32,kCpu,2000,500,1.332283
ExclusiveSum,int32,kCpu,5000,200,2.809763
ExclusiveSum,int32,kCpu,10000,100,5.249977
ExclusiveSum,int32,kCpu,100000,10,54.407120
ExclusiveSum,int32,kCuda,100,500,11.023936
ExclusiveSum,int32,kCuda,500,500,10.980480
ExclusiveSum,int32,kCuda,1000,500,11.052992
ExclusiveSum,int32,kCuda,2000,500,11.074368
ExclusiveSum,int32,kCuda,5000,200,11.086880
ExclusiveSum,int32,kCuda,10000,100,11.106239
ExclusiveSum,int32,kCuda,100000,10,11.392000
RowSplitsToRowIds,int32,kCpu,100,500,6.937981
RowSplitsToRowIds,int32,kCpu,500,500,38.788319
RowSplitsToRowIds,int32,kCpu,1000,500,91.593742
RowSplitsToRowIds,int32,kCpu,2000,500,187.736038
RowSplitsToRowIds,int32,kCpu,5000,200,458.455078
RowSplitsToRowIds,int32,kCpu,10000,100,1096.999634
RowSplitsToRowIds,int32,kCpu,100000,10,19828.986328
RowSplitsToRowIds,int32,kCuda,100,500,32.389694
RowSplitsToRowIds,int32,kCuda,500,500,39.937984
RowSplitsToRowIds,int32,kCuda,1000,500,39.807549
RowSplitsToRowIds,int32,kCuda,2000,500,39.866879
RowSplitsToRowIds,int32,kCuda,5000,200,73.464645
RowSplitsToRowIds,int32,kCuda,10000,100,118.126404
RowSplitsToRowIds,int32,kCuda,100000,10,933.507141
```

### CODE REVIEW

**Comment by qindazhu** [comment]
@csukuangfj , can you print the dim of `row_ids` besides the dim of `row_splits` here so we can compare the speed with `ExclusiveSum`, I just feel using 3 kenerls here is still slow. 

It would be better if you can add implementation with `Load Balancing Search` or `IntervalExpand ` in moderngpu and compare the performance, see here https://github.com/k2-fsa/k2/issues/252 for the link.
I think using `Load Balancing Search` would be straightforward, we can allocate an extra `0` at the begining of `row_splits` for now (if moderngpu requires that)

**Comment by csukuangfj** [comment]
Here is the result with row_ids dim info attached.
```
op_name,dtype,device,problem_size,number_of_iterations,elapsed_us_per_iteration
ExclusiveSum,int32,kCpu,100,500,0.390053
ExclusiveSum,int32,kCpu,500,500,0.577927
ExclusiveSum,int32,kCpu,1000,500,0.827789
ExclusiveSum,int32,kCpu,2000,500,1.304150
ExclusiveSum,int32,kCpu,5000,200,2.789497
ExclusiveSum,int32,kCpu,10000,100,5.209446
ExclusiveSum,int32,kCpu,100000,10,54.001808
ExclusiveSum,int32,kCuda,100,500,11.094336
ExclusiveSum,int32,kCuda,500,500,11.045824
ExclusiveSum,int32,kCuda,1000,500,11.098049
ExclusiveSum,int32,kCuda,2000,500,11.071553
ExclusiveSum,int32,kCuda,5000,200,11.130880
ExclusiveSum,int32,kCuda,10000,100,11.137280
ExclusiveSum,int32,kCuda,100000,10,12.064001
RowSplitsToRowIds_51408,int32,kCpu,100,500,6.909847
RowSplitsToRowIds_250461,int32,kCpu,500,500,39.572239
RowSplitsToRowIds_502975,int32,kCpu,1000,500,92.862129
RowSplitsToRowIds_996652,int32,kCpu,2000,500,179.075729
RowSplitsToRowIds_2485862,int32,kCpu,5000,200,452.024963
RowSplitsToRowIds_5009977,int32,kCpu,10000,100,1461.122070
RowSplitsToRowIds_50132078,int32,kCpu,100000,10,18816.208984
RowSplitsToRowIds_47545,int32,kCuda,100,500,31.913471
RowSplitsToRowIds_247474,int32,kCuda,500,500,40.188606
RowSplitsToRowIds_510764,int32,kCuda,1000,500,43.407684
RowSplitsToRowIds_1014597,int32,kCuda,2000,500,43.472710
RowSplitsToRowIds_2475739,int32,kCuda,5000,200,72.892319
RowSplitsToRowIds_5001882,int32,kCuda,10000,100,118.476807
RowSplitsToRowIds_49965586,int32,kCuda,100000,10,935.532776
```

`RowSplitsToRowIds_51408` means `row_ids.Dim() == 51408`.

**Comment by csukuangfj** [comment]
The result **before** the change:

```
op_name,dtype,device,problem_size,number_of_iterations,elapsed_us_per_iteration
ExclusiveSum,int32,kCpu,100,500,0.393867
ExclusiveSum,int32,kCpu,500,500,0.579834
ExclusiveSum,int32,kCpu,1000,500,0.818253
ExclusiveSum,int32,kCpu,2000,500,1.307964
ExclusiveSum,int32,kCpu,5000,200,2.819300
ExclusiveSum,int32,kCpu,10000,100,5.269051
ExclusiveSum,int32,kCpu,100000,10,65.112114
ExclusiveSum,int32,kCuda,100,500,12.664768
ExclusiveSum,int32,kCuda,500,500,12.622592
ExclusiveSum,int32,kCuda,1000,500,12.605888
ExclusiveSum,int32,kCuda,2000,500,12.609855
ExclusiveSum,int32,kCuda,5000,200,12.635520
ExclusiveSum,int32,kCuda,10000,100,12.618880
ExclusiveSum,int32,kCuda,100000,10,13.049600
RowSplitsToRowIds_52387,int32,kCpu,100,500,7.021904
RowSplitsToRowIds_246323,int32,kCpu,500,500,39.055824
RowSplitsToRowIds_496339,int32,kCpu,1000,500,86.837769
RowSplitsToRowIds_984132,int32,kCpu,2000,500,170.142166
RowSplitsToRowIds_2517967,int32,kCpu,5000,200,568.640259
RowSplitsToRowIds_5012810,int32,kCpu,10000,100,1142.120361
RowSplitsToRowIds_49885233,int32,kCpu,100000,10,21042.013672
RowSplitsToRowIds_51484,int32,kCuda,100,500,35.486149
RowSplitsToRowIds_251083,int32,kCuda,500,500,50.234623
RowSplitsToRowIds_502866,int32,kCuda,1000,500,71.606979
RowSplitsToRowIds_1010523,int32,kCuda,2000,500,126.360390
RowSplitsToRowIds_2491113,int32,kCuda,5000,200,234.021118
RowSplitsToRowIds_5002563,int32,kCuda,10000,100,443.293457
RowSplitsToRowIds_50034441,int32,kCuda,100000,10,4137.347168
```

**Comment by qindazhu** [comment]
thanks, seems we'll get 2-3x slower with 3 kenerls here than exclusivesum. let's try Load Balancing Search or IntervalExpand, hope we can get faster with them (comparable with a single exclusivesum call)

**Comment by csukuangfj** [comment]
To make the results comparable, the follow outputs are obtained by fixing the seed for the random generator:


## Result before the change

```
op_name,dtype,device,problem_size,number_of_iterations,elapsed_us_per_iteration
ExclusiveSum,int32,kCpu,100,500,0.631809
ExclusiveSum,int32,kCpu,500,500,1.023769
ExclusiveSum,int32,kCpu,1000,500,1.479626
ExclusiveSum,int32,kCpu,2000,500,2.279758
ExclusiveSum,int32,kCpu,5000,200,4.245043
ExclusiveSum,int32,kCpu,10000,100,5.240440
ExclusiveSum,int32,kCpu,100000,10,85.997581
ExclusiveSum,int32,kCuda,100,500,17.302784
ExclusiveSum,int32,kCuda,500,500,16.577984
ExclusiveSum,int32,kCuda,1000,500,13.375808
ExclusiveSum,int32,kCuda,2000,500,18.558720
ExclusiveSum,int32,kCuda,5000,200,18.921440
ExclusiveSum,int32,kCuda,10000,100,18.521280
ExclusiveSum,int32,kCuda,100000,10,48.505600
RowSplitsToRowIds_48549,int32,kCpu,100,500,11.497974
RowSplitsToRowIds_241752,int32,kCpu,500,500,35.412312
RowSplitsToRowIds_497635,int32,kCpu,1000,500,88.520050
RowSplitsToRowIds_985875,int32,kCpu,2000,500,194.337845
RowSplitsToRowIds_2510591,int32,kCpu,5000,200,835.615356
RowSplitsToRowIds_5005413,int32,kCpu,10000,100,2018.980957
RowSplitsToRowIds_49917013,int32,kCpu,100000,10,25229.001953
RowSplitsToRowIds_48549,int32,kCuda,100,500,26.983294
RowSplitsToRowIds_241752,int32,kCuda,500,500,45.857727
RowSplitsToRowIds_497635,int32,kCuda,1000,500,73.537476
RowSplitsToRowIds_985875,int32,kCuda,2000,500,118.802422
RowSplitsToRowIds_2510591,int32,kCuda,5000,200,238.892807
RowSplitsToRowIds_5005413,int32,kCuda,10000,100,445.678040
RowSplitsToRowIds_49917013,int32,kCuda,100000,10,4175.133301
```

## Result of this pullrequest

```
op_name,dtype,device,problem_size,number_of_iterations,elapsed_us_per_iteration
ExclusiveSum,int32,kCpu,100,500,0.396252
ExclusiveSum,int32,kCpu,500,500,0.582218
ExclusiveSum,int32,kCpu,1000,500,0.829697
ExclusiveSum,int32,kCpu,2000,500,1.299858
ExclusiveSum,int32,kCpu,5000,200,2.795458
ExclusiveSum,int32,kCpu,10000,100,5.218983
ExclusiveSum,int32,kCpu,100000,10,49.686432
ExclusiveSum,int32,kCuda,100,500,10.996544
ExclusiveSum,int32,kCuda,500,500,10.948096
ExclusiveSum,int32,kCuda,1000,500,10.927360
ExclusiveSum,int32,kCuda,2000,500,11.067776
ExclusiveSum,int32,kCuda,5000,200,11.160160
ExclusiveSum,int32,kCuda,10000,100,11.149440
ExclusiveSum,int32,kCuda,100000,10,11.721600
RowSplitsToRowIds_48549,int32,kCpu,100,500,6.619930
RowSplitsToRowIds_241752,int32,kCpu,500,500,37.623882
RowSplitsToRowIds_497635,int32,kCpu,1000,500,94.138145
RowSplitsToRowIds_985875,int32,kCpu,2000,500,204.528336
RowSplitsToRowIds_2510591,int32,kCpu,5000,200,481.150146
RowSplitsToRowIds_5005413,int32,kCpu,10000,100,2112.269287
RowSplitsToRowIds_49917013,int32,kCpu,100000,10,22779.892578
RowSplitsToRowIds_48549,int32,kCuda,100,500,41.246780
RowSplitsToRowIds_241752,int32,kCuda,500,500,47.868031
RowSplitsToRowIds_497635,int32,kCuda,1000,500,45.023685
RowSplitsToRowIds_985875,int32,kCuda,2000,500,44.249344
RowSplitsToRowIds_2510591,int32,kCuda,5000,200,73.912964
RowSplitsToRowIds_5005413,int32,kCuda,10000,100,120.770554
RowSplitsToRowIds_49917013,int32,kCuda,100000,10,936.143921
```

**Comment by csukuangfj** [comment]
> let's try Load Balancing Search or IntervalExpand, hope we can get faster with them (comparable with a single exclusivesum call)

Will try to implement them tomorrow.

**Comment by danpovey** [comment]
Cool!  Feel free to merge this and other stuff... my connection is very bad.

**Comment by csukuangfj** [comment]
ok, merge this pullrequest first. Will try the other method in the next commit.

**Comment by csukuangfj** [comment]
I confirm that `load balancing search` from `moderngpu` is much faster for `RowSplitsToRowIds`. Will make a PR.

**Pull request merged**
