### PR TITLE
Weight pushing for determinization

### PR DESCRIPTION
**Pull request by pkufool**
Finishing the remaining work in https://github.com/k2-fsa/k2/pull/790

### CODE REVIEW

**Comment by danpovey** [comment]
Great work!

**Comment by pkufool** [comment]
I think weight pushing for determinization is working now, visualize results are as follows:

BTW, current implementation of weight pushing will produce _**negative**_ scores, does it matter? @danpovey 

|Weight pushing|result|
|--|--|
|Original|image|
|kNoWeightPushing|image|
|kLogWeightPushing|image|
|kTripicalWeightPushing|image|

**Comment by danpovey** [comment]
The log and tropical weight pushing give the same score in this case, is it right?  I don't think it should be the same for this example.
Negative scores can be OK.

**Comment by pkufool** [comment]
Sorry, I was mistaken, fixed.
The picture in comments above is updated.

**Pull request merged**
