### PR TITLE
Implemented SegmentedExclusiveSum without cudpp, be more faster

### PR DESCRIPTION
**Pull request by qindazhu**
Will remove those cudpp file in a seperate PR.

### CODE REVIEW

**Comment by csukuangfj** [comment]
+2

**Comment by danpovey** [comment]
LGTM.. I assume you will run some comparison...

**Comment by qindazhu** [comment]
> LGTM.. I assume you will run some comparison...

Yeah, you can check it here https://github.com/k2-fsa/k2/pull/618#issuecomment-767343598, merging.

**Comment by danpovey** [comment]
I'm afraid this was problematic for large-sized inputs.
In testing of some FSA algorithms,  I discovered a situation where the SegmentedExclusiveSum of an array with nonnegative elements had some elements which were small and negative.

**Comment by danpovey** [comment]
I think we may need to revert to the cudpp approach.

**Comment by danpovey** [comment]
(This is for floats.  The current approach is probably OK for integers, due to properties of modular arithmetic.)

**Comment by qindazhu** [comment]
mm, OK, will do

**Comment by danpovey** [comment]
Mm, actually, if we used doubles (and we do in practice), this might not be such an issue.
IDK...

**Comment by qindazhu** [comment]
Let me revert to cudpp for now (and only for float and double, as the current approach would be faster for integer), I will try to implement an version `SegmentScan` based on modern gpu later, I found yesterday that it may be posibble to implement with modern gpu by using only one kenerl like `SegmentReduce` which is expected to be faster.

**Pull request merged**
