### PR TITLE
Implemented MapFsaVecStates

### PR DESCRIPTION
**Pull request by qindazhu**

### CODE REVIEW

**Comment by danpovey** [comment]
Cool!  Don't have time to check in detail, but looks OK at a glance.

**Comment by qindazhu** [comment]
Thanks, conflicts resolved, merging...if there's any issue, we can fix them later.

**Comment by danpovey** [comment]
Great!  Perhaps you can try to get the epsilon removal to run?
I finished the part that was unfinished.

**Comment by qindazhu** [comment]
No, I have not implementation of `ComputeEpsilonClosure(Iter)`, I was planning to do tomorrow.

**Comment by danpovey** [comment]
Ah OK, no problem, it can wait.

**Pull request merged**
