### PR TITLE
rename RemoveEpsilon to RemoveEpsilonPruned and fixed some bugs

### PR DESCRIPTION
**Pull request by qindazhu**
There are still some test failures, I'm working on them now. Just push for now to make you guys aware of that.

### CODE REVIEW

**Comment by qindazhu** [comment]
Noted all tests get passed now, ready to merge.
 ( I just found I have to delete folder `/build/lib` and then run `make` to override those old python files in `/build/lib`, I was thinking `make` will update it automatically..)

**Comment by csukuangfj** [comment]
> Noted all tests get passed now, ready to merge.
( I just found I have to delete folder /build/lib and then run make to override those old python files in /build/lib, I was thinking make will update it automatically..)

I think so. Do you have a folder `k2` inside `lib`? `k2` is copied to `lib` while building wheels.

**Comment by qindazhu** [comment]
> Do you have a folder `k2` inside `lib`? `k2` is copied to `lib` while building wheels.

yes, that's the order I build, I built with `make -j _k2` before and forgot to delete `lib`

**Comment by csukuangfj** [comment]
No need to delete lib. You only need to remove the folder `lib/k2`.

**Comment by qindazhu** [comment]
Yeah, I think so, thanks

**Comment by qindazhu** [comment]
Merging, if there's any issue, just leave your comments and I'll fix in next PR.

**Pull request merged**
