### PR TITLE
Add cuda support to GitHub actions

### LINKED ISSUE #319: build pip package automatically for dev purpose?
@csukuangfj Can you kindly build a latest pip package with master branch? And wondering if there's any way we can create pip package automatically every day (or when master is updated), for dev purpose for now?

### PR DESCRIPTION
**Pull request by csukuangfj**
Closes #319

Wheels are automatically built for every pullrequest and are saved on GitHub for downloading for 90 days.

The wheel packages for this pullrequest can be found at https://github.com/k2-fsa/k2/actions/runs/355073976

### CODE REVIEW

**Comment by danpovey** [comment]
Impressive!
How did you debug this?  Is there some kind of shell you can log into to debug the environment that's used for this build?
And are these builds uploaded to PyPi, or if not, how are they discovered when you do `pip install`?

**Comment by csukuangfj** [comment]
> How did you debug this? Is there some kind of shell you can log into to debug the environment that's used for this build?

The debug was done by fixing every error reported by GitHub Actions until there were no errors. I think it is not possible to
log into these machines.

These builds are not uploaded to PyPI, they are saved on GitHub instead. But it is possible to upload them to PyPI. We can create another action that is triggered whenever a new version is released and upload wheel files in this action.

To use `pip install`, we have to first download the artifact, unzip it to get the `*.whl` file, and then use `pip install` to install it.

I've downloaded one of the artifacts and tested it in this [colab notebook][1]. Everything works fine. So I think there is nothing wrong in the pip packages built by GitHub actions.

[1]: https://colab.research.google.com/drive/1YYjLEkphmPY1l5WoTqT86zpfVA3lLf4v?usp=sharing

**Comment by csukuangfj** [comment]
One drawback is that the file size of `libcontext.so` built by GitHub actions is about 3 times larger than the one built locally.

**Comment by danpovey** [comment]
Ah.
What do you think about renaming context to k2context?  The name is generic
enough that it can be confusable whether it comes from k2 or externally.

**Comment by csukuangfj** [comment]
I agree. Renamed.

**Comment by csukuangfj** [comment]
Ready to merge if there are no other problems/comments.

**Pull request merged**
