### PR TITLE
Fix computing bprop of GetTotScores.

### LINKED ISSUE #341: Backward of get_tot_scores ignores gradient
This is not right:
https://github.com/k2-fsa/k2/blob/59e7757c23e360acc5f655977683b2dfd8a3ce02/k2/python/k2/autograd.py#L55
the backward of get_tot_scores needs to multiply by the gradient at the output.
In our training, this is causing us to get the sign of the update wrong!!!

### PR DESCRIPTION
**Pull request by csukuangfj**
Closes #341 

TODOs:

- [x] Fix log-semiring

### CODE REVIEW

**Comment by csukuangfj** [comment]
Ready for review.

**Comment by qindazhu** [comment]
+2, the tot_objf now is decreasing, the only critical issue we have now is the out-of-memory issue.

**Comment by danpovey** [comment]
Great!  Let me merge this...

**Comment by danpovey** [comment]
The way I would try to debug this is first to add code in the tests of the individual things we backprop (tot-scores, etc.) to check that the CUDA memory used decreases to zero after all the objects are made unreachable.

**Pull request merged**
