### PR TITLE
WIP: Use cuSparse to compute csr2csc.

### PR DESCRIPTION
**Pull request by csukuangfj**
TODOs
- [ ] Compare the peformance of cuSparse and moderngpu for computing CSR2CSC

### CODE REVIEW

**Comment by csukuangfj** [comment]
Here is the profiling result.

I am not sure if the profiling method is correct or not. The test data is a randomly generated FsaVec and you can
find the test code in this pullrequest (it contains only a single `.cu` file.)

It turns out cuSparse is not faster than moderngpu in our case.  One possible reason is that
moderngpu sorts each Fsa separately in a cocurrent manner, whereas cuSparse transposes the whole FsaVec.

@danpovey  Do we need to replace moderngpu with cuSparse? Or do we need to transpose each Fsa separately with cuSparse?

```
open-source/k2/build$ nsys nvprof ./bin/cu_cusparse_test                                                                                                                                          
WARNING: cu_cusparse_test and any of its children processes will be profiled.                                                                                                                               
                                                                                                                                                                                                            
Collecting data...                                                                                                                                                                                          
Processing events...                                                                                                                                                                                        
Saving temporary "/tmp/nsys-report-67dc-4294-f0f9-4c70.qdstrm" file to disk...                                                                                                                              
Creating final output files...                                                                                                                                                                              
                                                                                                                                                                                                            
Processing [==============================================================100%]                                                                                                                             
Saved report file to "/tmp/nsys-report-67dc-4294-f0f9-4c70.qdrep"                                                                                                                                           
Exporting 22049546 events: [==============================================100%]                                                                                                                             
                                                                                                                                                                                                            
Exported successfully to                                                                                                                                                                                    
/tmp/nsys-report-67dc-4294-f0f9-4c70.sqlite                                                                                                                                                                 
                                                                                                                                                                                                            
Generating CUDA API Statistics...                                                                                                                                                                           
CUDA API Statistics (nanoseconds)                                                                                                                                                                           
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            
CUDA trace data was not collected.                                                                                                                                                                          
                                                                                                                                                                                                            
                                                                                                                                                                                                            
Generating NVTX Push-Pop Range Statistics...
NVTX Push-Pop Range Statistics (nanoseconds)
Time(%)      Total Time   Instances         Average         Minimum         Maximum  Range
-------  --------------  ----------  --------------  --------------  --------------  ----------------------------------------------------------------------------------------------------
   39.9     64820051497           6   10803341916.2      2229303430     43059184384  k2::FsaVec k2::RandomFsaVec(int32_t, int32_t, bool, int32_t, int32_t, int32_t)
   39.7     64570140302        1039      62146429.5        11583473     41131377200  k2::Fsa k2::RandomFsa(bool, int32_t, int32_t, int32_t)
    8.0     12939570005    20850070           620.6             163        10463727  int32_t k2::RandInt(int32_t, int32_t)
    5.0      8174703992        2098       3896427.1             186      8134041323  k2::Array1<T> k2::Array1<T>::To(k2::ContextPtr) const [with T = int; k2::ContextPtr = std::shared_pt
    5.0      8137665649           5    1627533129.8          213911      8136251441  k2::RaggedShape k2::RaggedShape::To(k2::ContextPtr) const
    0.9      1521757646        1039       1464636.8          588537        12645060  k2::RaggedShape k2::RandomRaggedShape(bool, int32_t, int32_t, int32_t, int32_t)
    0.5       818036644     1162177           703.9             216         5686603  int32_t k2::RandIntGeometric(int32_t, int32_t)
    0.1       243148982           5      48629796.4        18583700        95602954  k2::Ragged<T> k2::Stack(int32_t, int32_t, k2::Ragged<T>*) [with T = k2::Arc; int32_t = int]
    0.1       243086307           5      48617261.4        18580327        95557650  k2::Ragged<T> k2::Stack(int32_t, int32_t, k2::Ragged<T>**) [with T = k2::Arc; int32_t = int]
    0.1       174233496        3151         55294.7             268        47086781  void k2::MemoryCopy(void*, const void*, std::size_t, cudaMemcpyKind, k2::Context*)
    0.1       151366659           5      30273331.8        10191312        62371686  k2::Array1<T> k2::Append(int32_t, const k2::Array1<T>**) [with T = k2::Arc; int32_t = int]
    0.1        91993901        1038         88626.1           37023          555795  k2::Array1<T>::Array1(k2::ContextPtr, const std::vector<T>&) [with T = k2::Arc; k2::ContextPtr = std
    0.1        91603114           5      18320622.8         8373731        33144046  k2::RaggedShape k2::Stack(int32_t, int32_t, k2::RaggedShape**)
    0.1        87636652           5      17527330.4         8030190        31607523  k2::RaggedShape k2::Append(int32_t, int32_t, k2::RaggedShape**)
    0.0        63983487           5      12796697.4         2118565        47580549  k2::Array1<T> k2::Array1<T>::To(k2::ContextPtr) const [with T = k2::Arc; k2::ContextPtr = std::share
    0.0        62673314           5      12534662.8         2114038        47104460  void k2::Array1<T>::CopyFrom(const k2::Array1<T>&) [with T = k2::Arc]
    0.0        40724473        1064         38274.9             726         8150091  void k2::Array1<T>::CopyFrom(const k2::Array1<T>&) [with T = int]
    0.0        36757503        2078         17688.9            6756         1263388  bool k2::RaggedShape::Validate(bool) const
    0.0        35420698        3990          8877.4             172          585695  k2::Array1<int>& k2::RaggedShape::RowIds(int32_t)
    0.0        35075901        1039         33759.3           26176          254968  void k2::RaggedShape::Populate()
    0.0        29429167        1044         28188.9           22102          577887  void k2::RowSplitsToRowIds(k2::ContextPtr, int32_t, const int32_t*, int32_t, int32_t*)
    0.0         9864279        1044          9448.5            3525          393807  k2::Array1<T>::Array1(k2::ContextPtr, const std::vector<T>&) [with T = int; k2::ContextPtr = std::sh

    0.0         9241952           5       1848390.4          856040         3226414  cuSparse

    0.0         9229512           5       1845902.4          854272         3223824  k2::Array1<int> k2::GetTransposeReorderingCuSparse(cusparseHandle_t, k2::Ragged<int>&, int32_t)

    0.0         7094345        7023          1010.2             164          553065  int32_t k2::RaggedShape::TotSize(int32_t) const

    0.0         6801524           5       1360304.8         1198057         1628171  moderngpu

    0.0         6794496           5       1358899.2         1196453         1625794  k2::Array1<int> k2::GetTransposeReordering(k2::Ragged<int>&, int32_t)

    0.0         6787573           5       1357514.6         1194948         1623080  k2::Array1<int> k2::GetTransposeReorderingThreeAxesCuda(k2::Ragged<int>&, int32_t)
    0.0         6671305        6249          1067.6             160          552261  T k2::Array1<T>::operator[](int32_t) const [with T = int; int32_t = int]
    0.0         2357176           5        471435.2          292264          570876  std::vector<k2::RaggedShape> k2::UnsqueezeParallel(int32_t, k2::RaggedShape**, int32_t)
    0.0         2120063           5        424012.6          254216          670327  void k2::GetRowInfoMulti(int32_t, k2::RaggedShape**, k2::Array2<int*>*, k2::Array2<int*>*)
    0.0         2095785        2931           715.0             186          248292  k2::Array1<T> k2::Array1<T>::Range(int32_t, int32_t) const [with T = int; int32_t = int]
    0.0         1944223           5        388844.6          132910         1183245  k2::Array1<int> k2::GetDestStates(k2::FsaVec&, bool)
    0.0         1388676        2083           666.7             180          111450  void k2::Array1<T>::operator=(T) [with T = int]
    0.0          687648           5        137529.6           38592          468997  k2::Array1<T> k2::Array1<T>::Clone() const [with T = int]
    0.0          402022          10         40202.2           10530          146430  k2::Array1<T> k2::Range(k2::ContextPtr, int32_t, T, T) [with T = int; k2::ContextPtr = std::shared_p
    0.0          158212           5         31642.4           24717           46332  k2::Array1<T> k2::Array1<T>::operator[](const k2::Array1<int>&) const [with T = int]
    0.0          157637           5         31527.4            5265           79024  k2::RaggedShape k2::RaggedShapeFromTotSizes(k2::ContextPtr, int32_t, int32_t*)
    0.0           93943           5         18788.6           13113           26336  void k2::Array1<T>::Index(const k2::Array1<int>&, k2::Array1<T>*) const [with T = int]
    0.0           52433          15          3495.5            2023            5676  void k2::GetTaskRedirect(cudaStream_t, int32_t, const int32_t*, k2::TaskRedirect*)
    0.0            7314          10           731.4             277            1465  k2::Array2<T> k2::Array2<T>::To(k2::ContextPtr) const [with T = int*; k2::ContextPtr = std::shared_p
    0.0            3256           5           651.2             327             835  k2::Array2<T> k2::Array2<T>::To(k2::ContextPtr) const [with T = int; k2::ContextPtr = std::shared_pt
    0.0            2563           5           512.6             276             873  int32_t k2::RoundUpToNearestPowerOfTwo(int32_t)

```

**Comment by danpovey** [comment]
If there isn't a way to do multiple problems at the same time with
cuSparse, we should probably keep the moderngpu implementation.
But you could leave the PR up in case we need that code for something in
the future.

**Comment by danpovey** [comment]
[I wrote this earlier but the email bounced]:

If there isn't a way to do multiple problems at the same time with cuSparse, we should probably keep the moderngpu implementation.
But you could leave the PR up in case we need that code for something in the future.

**Comment by csukuangfj** [comment]
I just modified the code to let modergpu sort the whole FsaVec at once instead of sorting single Fsas concurrently:

```
diff --git a/k2/csrc/ragged_ops.cu b/k2/csrc/ragged_ops.cu
index 18a353d..db97180 100644
--- a/k2/csrc/ragged_ops.cu
+++ b/k2/csrc/ragged_ops.cu
@@ -1068,8 +1068,8 @@ Array1<int32_t> GetTransposeReordering(Ragged<int32_t> &src, int32_t num_cols) {

   K2_CHECK_EQ(device_type, kCuda);

-  if (src.NumAxes() == 3)
-    return GetTransposeReorderingThreeAxesCuda(src, num_cols);
+  // if (src.NumAxes() == 3)
+  //   return GetTransposeReorderingThreeAxesCuda(src, num_cols);

   const int32_t *row_splits1_data = src.RowSplits(src.NumAxes() - 1).Data();
   const int32_t *row_ids1_data = src.RowIds(src.NumAxes() - 1).Data();
```


The profiling result shows that moderngpu is still faster:

```
    0.0        34654074        2078         16676.6            6883          381449  bool k2::RaggedShape::Validate(bool) const

    0.0        34027633        1039         32750.4           26100          280247  void k2::RaggedShape::Populate()

    0.0        33332437        3918          8507.5             173          294908  k2::Array1<int>& k2::RaggedShape::RowIds(int32_t)

    0.0        28759985        1044         27547.9           22062          287667  void k2::RowSplitsToRowIds(k2::ContextPtr, int32_t, const int32_t*, int32_t, int32_t*)
    0.0        12792528           5       2558505.6          827584         5138487  cuSparse

    0.0        12771426           5       2554285.2          826193         5135423  k2::Array1<int> k2::GetTransposeReorderingCuSparse (cusparseHandle_t, k2::Ragged<int>&, int32_t)
    0.0        10315868        1044          9881.1            2646          316614  k2::Array1<T>::Array1(k2::ContextPtr, const std::v ector<T>&) [with T = int; k2::ContextPtr = std::sh
    0.0         6247379           5       1249475.8         1044130         1570105  moderngpu

    0.0         6237254           5       1247450.8         1041590         1568730  k2::Array1<int> k2::GetTransposeReordering(k2::Ragged<int>&, int32_t)
    0.0         6136689        6249           982.0             167          566525  T k2::Array1<T>::operator[](int32_t) const [with T= int; int32_t = int]
```

---

I will close this pullrequest. If at some point we want to use cuSparse, the code in this pullrequest may be used as an example
for how to use cuSparse.

**Pull request closed without merging**
