### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by csukuangfj**
Users do not need to install CUDA toolkit to run k2.

@qindazhu Please have a review.

### CODE REVIEW

**Comment by qindazhu** [comment]
+1, merge

**Comment by danpovey** [comment]
Have we tested this?  Wouldn't it try to dynamically load libraries from
the CUDA toolkit?

**Comment by csukuangfj** [comment]
Yes, I have verified it locally on a virtual machine with Ubuntu 18.04. There are no GPUs or CUDA toolkit on the VM. I only need to install torch==1.6.0+cu101 and install k2 downloaded from GitHub actions. All  Python tests get passed.

GetCudaContext will not be called in this case since all Python tests will not use GPU if torch.cuda.is_available() returns False.




Thursday, 26 November 2020, 12:06 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by danpovey** [comment]
And all CPU tests?  Surely it would try to load the CUDA library to see if
a GPU is available?

**Comment by csukuangfj** [comment]
Yes, all CPU tests got passed.

You can see from the following output that there is a function `_lazy_init`, which is not called if we do
not access the GPU.

```
$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
>>> a = torch.arange(3)
>>> a.cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fangjun/sdb1/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 186, in _lazy_init
    _check_driver()
  File "/home/fangjun/sdb1/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 68, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
>>> import k2
>>> s = '''0 1 -1 0\n1'''
>>> fsa = k2.Fsa.from_str(s)
>>> fsa = fsa.to(torch.device('cuda', 0))
[W] /home/runner/work/k2/k2/k2/csrc/pytorch_context.cu:operator():126 CUDA is not available. Return a CPU context.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fangjun/sdb1/py36/lib/python3.6/site-packages/k2/fsa.py", line 688, in to
    phantom_set_scores_to(ans, self.scores.to(device))
  File "/home/fangjun/sdb1/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 186, in _lazy_init
    _check_driver()
  File "/home/fangjun/sdb1/py36/lib/python3.6/site-packages/torch/cuda/__init__.py", line 68, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

**Comment by csukuangfj** [comment]
RE CPU tests, i.e., C++ tests, they are all passed without GPU as can be seen from
https://github.com/k2-fsa/k2/actions?query=workflow%3Arun-tests

However, the **Release** build will segfault on GitHub actions, which I cannot reproduce locally.
Add C++ tests are able to run without the need of a GPU.

To run C++ tests, they have to be compiled first, which means CUDA toolkit has to be installed.

**Comment by danpovey** [comment]
can you show the url where the C++ tests are failing in release?
I can try to repro on a remote machine I have.

**Comment by csukuangfj** [comment]
I commented on it at https://github.com/k2-fsa/k2/issues/353#issuecomment-732478499

One of the URLs is https://github.com/k2-fsa/k2/runs/1440725780?check_suite_focus=true#step:11:276

> /home/runner/work/_temp/24ef5e13-3c98-46fb-9c31-b30c4a1e294d.sh: line 4: 16032 Segmentation fault      (core dumped) ./bin/cu_fsa_algo_test

**Comment by danpovey** [comment]
Hm.  I wonder if we could modify the scripts so it will run with valgrind
on failure, to get a stack trace?
I wasn't able to install CUDNN to make the installation work on that
machine, NVidia makes it too hard to download.

**Comment by csukuangfj** [comment]
@danpovey 
Here is the stack trace using the latest master

https://github.com/csukuangfj/k2/runs/1457937727?check_suite_focus=true#step:11:312

**Comment by danpovey** [comment]
ChangeSublistSize() and Transpose() (in ragged_ops.cu) both contain very short lambdas.
I think it's that compiler bug we previously encountered.  I think those should be replaced with
an if-statement where one branch uses a loop on CPU and the other calls EvalDevice()
using a __device__ macro.

Incidentally, it would be good if we could make minimal repo where we demonstrate this bug, so NVidia
can perhaps fix it (or confirm that it's already fixed, in later versions of their toolkit).
I wonder whether @jimbozhang  could try to do that?

**Comment by csukuangfj** [comment]
> I think those should be replaced with
an if-statement where one branch uses a loop on CPU and the other calls EvalDevice()
using a __device__ lambda.

I have updated the code and am waiting to see whether GitHub actions will segfault or not.

**Comment by csukuangfj** [comment]
Replacing short lambdas with `if + for`  is not able to prevent segfault in GitHub actions for `Release` build.
After some trial-and-error attempts, I managed to avoid segfault by replacing GCC 5 with GCC 6 and GCC 7
without changing a signle line of C++ code. Will create a pullrequest.

**Pull request merged**
