### PR TITLE
Hybrid autoregressive transducer (HAT)

### PR DESCRIPTION
**Pull request by desh2608**
This is an implementation of the HAT loss proposed in https://arxiv.org/abs/2003.07705.

The test produces reasonable looking losses. I am working on a LibriSpeech zipformer recipe using this loss. In general, it is not expected to improve upon the RNNT loss by itself, but may be useful for things like using external LMs. I am planning to use it in multi-talker ASR for speaker attribution (e.g. https://arxiv.org/abs/2309.08489)

### CODE REVIEW

**Comment by danpovey** [comment]
Great!

**Comment by desh2608** [comment]
@csukuangfj could you also check this when you have some time? Thanks!

**Comment by csukuangfj** [comment]
> @csukuangfj could you also check this when you have some time? Thanks!

Thanks! Left a minor comment. Otherwise, it looks good to me.

**Comment by desh2608** [comment]
> > @csukuangfj could you also check this when you have some time? Thanks!
> 
> Thanks! Left a minor comment. Otherwise, it looks good to me.

Sorry it took a while since I was on vacation last 2 weeks. I have made the change.

**Comment by csukuangfj** [comment]
Thanks!

**Pull request merged**
