### PR TITLE
Ignore strides CHECK in FromTorch when input tensor is empty

### PR DESCRIPTION
**Pull request by pkufool**
See https://github.com/k2-fsa/snowfall/pull/227#issuecomment-877945713

### CODE REVIEW

**Comment by csukuangfj** [comment]
@glynpu 
Could you try this pull request and see if it solves the issue in
https://github.com/k2-fsa/snowfall/pull/227#issuecomment-873777500

**Comment by pkufool** [comment]
I think this PR do solve the issue (https://github.com/k2-fsa/snowfall/pull/227#issuecomment-873777500), apart from the stride checking problem, there is also a bug in `Transpose` that return "null" `index_values` when the input is empty FsaVec (with no fsa at all). 
Actually, there are two kinds of Array1 with Dim() equals to zero, one is constructed from default constructor (`region_ == nullptr`), the other is constructed from `Array1(ContextPtr c, int32_t size)` with size equals to zero. And, many of the functions can not handle the first one as input, because we would call `GetContext()` at beginning which causes crash. Do we need a CHECK at these functions or return directly when the input Array1 with a nullptr region.

**Comment by pkufool** [comment]
I want to add a test case to cover the empty FsaVec, but I didn't find a way to construct a empty FsaVec.

I thought there are some kinds of FsaVec, the first, FsaVec without any fsa (this kind cause this crash), the second, FsaVec contains empty fsas without states, the third, FsaVec contains empty fsas with states(surely no arcs).

**Comment by danpovey** [comment]
> I think this PR do solve the issue ([k2-fsa/snowfall#227 (comment)](https://github.com/k2-fsa/snowfall/pull/227#issuecomment-873777500)), apart from the stride checking problem, there is also a bug in `Transpose` that return "null" `index_values` when the input is empty FsaVec (with no fsa at all).
> Actually, there are two kinds of Array1 with Dim() equals to zero, one is constructed from default constructor (`region_ == nullptr`), the other is constructed from `Array1(ContextPtr c, int32_t size)` with size equals to zero. And, many of the functions can not handle the first one as input, because we would call `GetContext()` at beginning which causes crash. Do we need a CHECK at these functions or return directly when the input Array1 with a nullptr region.

An Array1 that's default-constructed, with no region, is considered invalid.  That is, it should not appear as an input argument to functions, and should not be produced as output from a function that had valid inputs.  It can be considered an error, or just lead to a crash, if passed into a function.

**Comment by danpovey** [comment]
@pkufool feel free to merge if you think this is ready.

**Comment by csukuangfj** [comment]
@danpovey Could you give @pkufool merge permissions for this repo?  I guess he does not have merge permissions.

**Pull request merged**
