### PR TITLE
Refactor Fsa in Python.

### PR DESCRIPTION
**Pull request by csukuangfj**
Implement `__getattr__` and `__setattr__` of `Fsa` in Python.

### CODE REVIEW

**Comment by csukuangfj** [comment]
No tests for `FsaVec` since `FsaVecFromArray1` has not been implemented in C++.

**Comment by csukuangfj** [comment]
> The `__setattr__` will just check that the first index equals the `arcs.numel()`, and set it in the dict. However, if it is the .weight attribute it will also overwrite the weights in the FSA with it, i.e. the .scores field, in addition to setting the class member.

> Note: we will always create an attribute called '.scores' when we construct an FSA, e.g. from a tensor. This .scores attribute will be parallel to the .score field of the arcs, the idea is that they will always be the same (but separately stored). If the user overwrites the .scores field, we will also automatically overwrite the .score elements of the arcs.

The implementation does not follow the above description striclty. However, I think it achieves the same effect.

**Comment by danpovey** [comment]
Great work!  Had a quick look and didn't see any problems.  Let me leave this up a little in case of other comments, then merge.

**Comment by qindazhu** [comment]
+1

**Comment by danpovey** [comment]
OK to merge if you think its OK

**Pull request merged**
