### PR TITLE
Implemented ComputeEpsilonClosure

### PR DESCRIPTION
**Pull request by qindazhu**

### CODE REVIEW

**Comment by danpovey** [comment]
Great work!!!
I'll merge this, but don't forget to add random tests!

**Comment by danpovey** [comment]
Also you might want to test with simple examples that it does what we intended about combining epsilons with either the following or preceding arcs depending what would be more efficient.

**Comment by qindazhu** [comment]
Definitely yes, I have 3 functions needed to be add random tests in rm_epsilon, `MapFsaVecStates`, `ComputeEpsilonClosure(Iter)`, will do later). Thanks

**Comment by qindazhu** [comment]
> we intended about combining epsilons with either the following or preceding arcs depending what would be more efficient.

Yeah, but actually I have not run `RemoveEpsilonsIterativeTropical`.. will do later.

**Comment by qindazhu** [comment]
Merging..

**Pull request merged**
