### PR TITLE
revert to use cudpp for float type in SegmentedExclusiveSum

### PR DESCRIPTION
**Pull request by qindazhu**
@danpovey  Reverted for float and double. I will try to implement `SegmentedScan` based on modern gpu later (after I get more familiar with its code)

Only need to review file `ragged_ops_inl.h`, other files are just copied from PR https://github.com/k2-fsa/k2/pull/618

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks!  If you have time, would you mind uncommenting the floating-point version of the test for RandomPaths() in fsa_utils_test.cu, and see if it works now?

**Comment by danpovey** [comment]
OK to merge if that works.

**Comment by qindazhu** [comment]
seems cudpp still does not work for float...

```
[I] /ceph-hw/k2/k2/csrc/ragged_ops_inl.h:void k2::SegmentedExclusiveSum(k2::Ragged<T>&, k2::Array1<T>*) [with T = float]:595 ragged float
[F] /ceph-hw/k2/k2/csrc/fsa_utils_test.cu:lambda [](signed int)->auto::operator()(signed int)->auto:1165 block:[2,0,0], thread: [68,0,0] Check failed: cdf_val >= arc_cdf_data[arc_idx012 - 1] (0.016467 vs. 0.016467)
/ceph-hw/k2/k2/csrc/fsa_utils_test.cu:1165: lambda [](signed int)->auto::operator()(signed int)->auto: block: [2,0,0], thread: [68,0,0] Assertion `Some bad things happened` failed.
[F] /ceph-hw/k2/k2/csrc/array.h:T k2::Array1<T>::operator[](int32_t) const [with T = int; int32_t = int]:275 Check failed: ret == cudaSuccess (710 vs. 0)  Error: device-side assert triggered.

```

(BTW, cudpp may need some instatiation for `double`, will look into tomorrow)

**Comment by danpovey** [comment]
OK.  Let me try to fix it a different way.. I'll merge anyway.

**Comment by csukuangfj** [comment]
CUDPP in k2 supports only int32_t and float (I removed double). Adding support for `double` is not difficult.

**Comment by qindazhu** [comment]
can u help to add the support for double as u may be more familiar with that codebase?

**Comment by csukuangfj** [comment]
Sure, I will add support for `double` tomorrow morning.

**Pull request merged**
