### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by csukuangfj**
As mentioned in https://github.com/k2-fsa/k2/pull/855#issue-1039247242,
this PR removes unused code, e.g., those related to autograd in C++.

Also, keep v2.0-pre synced with the master.

### CODE REVIEW

**Comment by pkufool** [comment]
@csukuangfj  Did you revert all the commits related to the "Move Fsa to C++" (i.e the RaggedArc thing)?

**Comment by csukuangfj** [comment]
> @csukuangfj  Did you revert all the commits related to the "Move Fsa to C++" (i.e the RaggedArc thing)?

Yes. I think it would be easier to add new code than to modify the existing code. You can add the code that is actually needed.

**Comment by pkufool** [comment]
> Yes. I think it would be easier to add new code than to modify the existing code. You can add the code that is actually needed.

Yes, I think so. Thanks! I will start from this pull request.

**Comment by pkufool** [comment]
> > @csukuangfj  Did you revert all the commits related to the "Move Fsa to C++" (i.e the RaggedArc thing)?
> 
> Yes. I think it would be easier to add new code than to modify the existing code. You can add the code that is actually needed.

**Comment by pkufool** [comment]
I thought your torchscript demo were based on `RaggedArc`, will read the demo code carefully again.

**Pull request merged**
