### PR TITLE
Declare MonotonicLowerBound

### PR DESCRIPTION
**Pull request by danpovey**
Would be nice if someone can implement this.  Will be needed for the forward-backward algorithm, to compute batches.

### CODE REVIEW

**Comment by qindazhu** [comment]
OK, will do later today.

**Comment by danpovey** [comment]
Wait, just realized I don't need this right now after all.  Do it if you
want anyway though.

**Comment by qindazhu** [comment]
mm. Sorry, didn't check the messages...I have finished the code..

**Comment by danpovey** [comment]
Fantastic!

**Pull request merged**
