### PR TITLE
Support compiling k2 on macOS/Linux/Windows without installing CUDA toolkit.

### PR DESCRIPTION
**Pull request by csukuangfj**
Now, k2 can be compiled and run on macOS (without an NVIDIA GPU and without installing CUDA toolkit)

- [x] Add GitHub actions to build k2  on macOS
- [x] Build conda packages for macOS
- [x] Build pip packages for macOS
- [ ] Update documentation to describe how to compile k2 on macOS
---

All tests passed on my macOS, except for `cu_top_sort_test`. I'm trying to find out the reason for the failure.

---

To build k2 without CUDA, use
```
mkdir build_release
cd build_release
cmake -DK2_WITH_CUDA=OFF -DCMAKE_BUILD_TYPE=Release ..
```

or  use

```
cd /path/to/k2
export K2_CMAKE_ARGS="-DK2_WITH_CUDA=OFF -DCMAKE_BUILD_TYPE=Release"
python3 setup.py install
```

- For macOS, `K2_WITH_CUDA` is OFF by default.
- For Linux, `K2_WITH_CUDA` is ON by default.

### CODE REVIEW

**Comment by danpovey** [comment]
Wow, that was a lot of work!
It looks OK to me...

**Comment by pzelasko** [comment]
Imagine what fun it will be to add the support for native Windows :)

**Comment by csukuangfj** [comment]
> All tests passed on my macOS, except for cu_top_sort_test. I'm trying to find out the reason for the failure.

Turns out there was a bug. It's fixed in the commit https://github.com/k2-fsa/k2/pull/748/commits/f55ae669d73c1330f4a17d8e3becf2308439e0f4 within this pull request.

---

Now, k2 can be built without CUDA support, i.e, using only CPU without installing CUDA toolkit, on Linux, macOS, and Windows.

Prebuilt wheels by GitHub actions can be found in the following links:

## Linux and macOS

https://github.com/k2-fsa/k2/actions/runs/892894495

Screen Shot 2021-06-01 at 9 04 23 PM

## Windows

https://github.com/k2-fsa/k2/actions/runs/896041166

Screen Shot 2021-06-01 at 9 09 01 PM

---

Will add support to upload them to pypi and k2-fsa.org

**Comment by csukuangfj** [comment]
To install a CPU version of k2 using conda for
- macOS
- Linux
- Windows

You can run

```bash
conda install cpuonly k2 python=3.8 pytorch=1.7.1 -c k2-fsa -c pytorch
```

(NOTE: The command is the same for the three operating systems.)

---

Visit https://anaconda.org/k2-fsa/k2/files for available combinations of Python versions and PyTorch versions.
Screen Shot 2021-06-02 at 2 40 16 PM

**Comment by jtrmal** [comment]
Hi, what is the correct way with just pip? Thanks and sorry for the trouble.
y.

**Comment by csukuangfj** [comment]
> Hi, what is the correct way with just pip? Thanks and sorry for the trouble.


We've uploaded the pre-built wheel packages to https://k2-fsa.org/nightly/index.html

Screen Shot 2021-06-02 at 6 28 16 PM


You can go to that page and download a wheel with desired Python version and PyTorch version.

For instance,
```
wget https://k2-fsa.org/nightly/whl/k2-0.3.4.dev20210602+cpu.torch1.7.0-cp36-cp36m-macosx_10_15_x86_64.whl
pip install ./k2-0.3.4.dev20210602+cpu.torch1.7.0-cp36-cp36m-macosx_10_15_x86_64.whl
```

Alternatively, you can use
```
# It works for Linux/macOS/Windows
pip install k2==0.3.4.dev20210602+cpu.torch1.7.0 -f https://k2-fsa.org/nightly/
```

**Comment by jtrmal** [comment]
oh, obviously. Yeah, I should have think of that... Thanks!
y.

**Comment by csukuangfj** [comment]
Ready for review and merge.

Most of the changes from the last review are from the CI scripts.

**Comment by csukuangfj** [comment]
Will add CUDA version for Windows and documentation in a separate pull-request.

**Review by danpovey — COMMENTED** [review]
There is a lot here that I don't understand, but what I've seen look good.
How does the conda build happen-- is somehow automatic on github, or do you have to do something manually?

**Comment by csukuangfj** [comment]
> How does the conda build happen-- is somehow automatic on github, or do you have to do something manually?

For Linux and Windows, yes. Whenever you push to the branch `conda`, GitHub actions will be triggered to build conda
packages and upload them to anaconda.org.

As for the macOS, I noted in the file
https://github.com/k2-fsa/k2/blob/ca06656b6209609f25bbde4a699cb4d3d3cceab9/.github/workflows/build_conda_cpu.yml#L8-L17
It happens only for GitHub actions and works fine when bulding locally.

Currently, I am building conda packages for macOS locally/manually and uploading them to anaconda.org by myself.

---

For building pip packages, GitHub actions handle that automatically when you push to the branch `wheel`.

**Comment by danpovey** [comment]
Cool!
You can merge when you want; I'm afraid I won't be much help checking this.

**Comment by pzelasko** [comment]
@csukuangfj I think you accidentally broke anaconda CUDA k2 build. I updated k2 from conda using:

```
$ conda remove k2
$ conda install -c pytorch -c k2-fsa -c conda-forge k2
```

The conformer mmi script just exited with a segmentation fault in one of the spawned workers. Only when I removed `mp.spawn` and ran it through GDB, I discovered this (notice the warning):

```
Added key: store_based_barrier_key:1 to store for rank: 0
[New Thread 0x2aab4743b700 (LWP 235543)]
Loading lexicon and symbol tables
Loading L.fst
[W] /usr/share/miniconda/envs/k2/conda-bld/k2_1622614684447/work/build/temp.linux-x86_64-3.8/k2/csrc/pytorch_context.cc:67:void k2::InitHasCuda() k2 was not compiled with CUDA. Return a CPU context.
[New Thread 0x2aab4723a700 (LWP 235544)]
[Thread 0x2aab4723a700 (LWP 235544) exited]
Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x555558b9bd10, tinfo=0x2aaad3638870 <typeinfo for c10::Error>, dest=0x2aab1fc6c0a0 <c10::Error::~Error()>)
    at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:80
80      /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc: No such file or directory.
Missing separate debuginfos, use: debuginfo-install flac-libs-1.3.0-5.el7_1.x86_64 glibc-2.17-222.el7.x86_64 gsm-1.0.13-11.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libsndfile-1.0.25-10.el7.x86_64 libvorbis-1.3.3-8.el7.1.x86_64 nvidia-driver-latest-cuda-libs-460.32.03-1.el7.x86_64
```

**Comment by pzelasko** [comment]
(BTW I think messages like these should be propagated to and displayed in Python)

**Comment by csukuangfj** [comment]
@pzelasko 

If you look carefully at the output of
```
conda install -c pytorch -c k2-fsa -c conda-forge k2
```
You will find something like

Screen Shot 2021-06-03 at 10 28 58 AM

Note there is `cpuonly` in the above screenshot.

That means you're installing a CPU version of k2 and PyTorch.

That is not a problem before, since there was only CUDA versions of k2 in the anaconda channel `k2-fsa`.
Things change after this pull-request. There are also CPU versions of k2 in the anaconda.

So the correct way to install k2, as stated explicitly in the documentation https://k2.readthedocs.io/en/latest/installation/conda.html#install-using-conda , 
is
```bash
$ conda install -c k2-fsa -c pytorch -c conda-forge k2 python=3.8 cudatoolkit=11.1 pytorch=1.8.1
```

You omitted `cudatoolkit=11.1` in your command, so it installed a CPU version.

You can change the version of `cudatoolkit`, but you cannot leave it out.

**Comment by csukuangfj** [comment]
> BTW I think messages like these should be propagated to and displayed in Python

It is displayed in the console by deafult. If you're using a jupyter notebook, please use
```python
try:
  ... <your code here>
except RuntimeException as e:
  print(e)
```
to catch the exception. If not, it aborts the program.

**Comment by csukuangfj** [comment]
I am merging it.

Also, only one CUDA version of k2 will be kept in anaconda.org, as there is not enough space with it.
See
Screen Shot 2021-06-03 at 3 54 58 PM

**Comment by pzelasko** [comment]
> > BTW I think messages like these should be propagated to and displayed in Python
> 
> It is displayed in the console by deafult. If you're using a jupyter notebook, please use
> 
> ```python
> try:
>   ... <your code here>
> except RuntimeException as e:
>   print(e)
> ```
> 
> to catch the exception. If not, it aborts the program.

FYI it was not in Jupyter -- that was a command line script and there was no message about this.

**Comment by csukuangfj** [comment]
> > > BTW I think messages like these should be propagated to and displayed in Python
> 
> > 
> 
> > It is displayed in the console by deafult. If you're using a jupyter notebook, please use
> 
> > 
> 
> > ```python
> 
> > try:
> 
> >   ... <your code here>
> 
> > except RuntimeException as e:
> 
> >   print(e)
> 
> > ```
> 
> > 
> 
> > to catch the exception. If not, it aborts the program.
> 
> 
> 
> FYI it was not in Jupyter -- that was a command line script and there was no message about this. 

I see. The error is from PyTorch, as it passes a CPU address, where a GPU address is expected. Don't know why the warning message from k2 doesn't show up in the stderr.

**Comment by jtrmal** [comment]
great job -- was able both install from wheel but also compile on my mac
without any issues. Also all tests run fine.
y.

**Pull request merged**
