### PR TITLE
add ArcSort for FsaVec.

### LINKED ISSUE #219: Bugs in GetFsaBasicProperties
For the following fsa
https://github.com/k2-fsa/k2/blob/d291daf7a88d50907d2b1039ca6033f307995a65/k2/csrc/fsa_algo_test.cu#L26-L38

It prints
```
"Valid|Nonempty|TopSorted|TopSortedAndAcyclic|ArcSortedAndDeterministic|EpsilonFree|MaybeAccessible|Serializable"
```

----

**ArcSortedAndDeterministic** should NOT be there.

### PR DESCRIPTION
**Pull request by csukuangfj**
This closes  #219

### CODE REVIEW

**Comment by danpovey** [comment]
looks good.. not merging as WIP but you can merge when you think it's done unless there is something you think will be controversial.

**Comment by csukuangfj** [comment]
WIP because of #222

**Comment by csukuangfj** [comment]
Ready to review.

**Comment by qindazhu** [comment]
I'm OK to merge. Just note that  CPU version of `SortSubLists` has not implemented for now ( maybe similar code with `/host/arcsort.cc` )

**Comment by csukuangfj** [comment]
> I'm OK to merge. Just note that CPU version of SortSubLists has not implemented for now ( maybe similar code with /host/arcsort.cc )

Support for CPU can be added in another pullrequest.

**Pull request merged**
