### PR TITLE
kmp-LCP: sequential LCP algorithm of Karkkainen et al.

### PR DESCRIPTION
**Pull request by mahsa7823**

### CODE REVIEW

**Comment by danpovey** [comment]
@pkufool would you mind checking this over quickly, testing if you feel, necessary, and merge?
Mahsa says this is faster.   Probably not necessary to check that if a test is not already there though,
I'm willing to take her word for it.

**Comment by pkufool** [comment]
> @pkufool would you mind checking this over quickly, testing if you feel, necessary, and merge?
> Mahsa says this is faster. Probably not necessary to check that if a test is not already there though,
> I'm willing to take her word for it.

I will do it right now.

**Comment by pkufool** [comment]
array len : 516 time used for old : 0.031000 s time used for new : 0.014000 s                                                                                                                 
array len : 532 time used for old : 0.032000 s time used for new : 0.014000 s                                                                                                                 
array len : 630 time used for old : 0.037000 s time used for new : 0.016000 s                                                                                                                 
array len : 632 time used for old : 0.038000 s time used for new : 0.016000 s                                                                                                                 
array len : 774 time used for old : 0.046000 s time used for new : 0.019000 s                                                                                                                 
array len : 777 time used for old : 0.046000 s time used for new : 0.019000 s                                                                                                                 
array len : 798 time used for old : 0.046000 s time used for new : 0.019000 s                                                                                                                 
array len : 823 time used for old : 0.047000 s time used for new : 0.018000 s                                                                                                                 
array len : 826 time used for old : 0.051000 s time used for new : 0.019000 s                                                                                                                 
array len : 843 time used for old : 0.049000 s time used for new : 0.020000 s                                                                                                                 
array len : 870 time used for old : 0.053000 s time used for new : 0.022000 s                                                                                                                 
array len : 946 time used for old : 0.053000 s time used for new : 0.021000 s                                                                                                                 
array len : 957 time used for old : 0.053000 s time used for new : 0.020000 s                                                                                                                 
array len : 1040 time used for old : 0.058000 s time used for new : 0.022000 s                                                                                                                
array len : 1040 time used for old : 0.059000 s time used for new : 0.023000 s                                                                                                                
array len : 1188 time used for old : 0.068000 s time used for new : 0.026000 s                                                                                                                
array len : 1236 time used for old : 0.070000 s time used for new : 0.026000 s                                                                                                                
array len : 1429 time used for old : 0.081000 s time used for new : 0.029000 s                                                                                                                
array len : 1591 time used for old : 0.086000 s time used for new : 0.030000 s                                                                                                                
array len : 1601 time used for old : 0.089000 s time used for new : 0.031000 s                                                                                                                
array len : 1667 time used for old : 0.090000 s time used for new : 0.031000 s                                                                                                                
array len : 1719 time used for old : 0.094000 s time used for new : 0.032000 s                                                                                                                
array len : 1767 time used for old : 0.095000 s time used for new : 0.033000 s                                                                                                                
array len : 1830 time used for old : 0.099000 s time used for new : 0.034000 s                                                                                                                
array len : 1869 time used for old : 0.103000 s time used for new : 0.035000 s                                                                                                                
array len : 1945 time used for old : 0.106000 s time used for new : 0.036000 s                                                                                                                
array len : 1948 time used for old : 0.107000 s time used for new : 0.036000 s                                                                                                                
array len : 1949 time used for old : 0.108000 s time used for new : 0.040000 s                                                                                                                
array len : 2016 time used for old : 0.109000 s time used for new : 0.035000 s                                                                                                                
array len : 2034 time used for old : 0.112000 s time used for new : 0.038000 s                                                                                                                
array len : 2050 time used for old : 0.112000 s time used for new : 0.037000 s                                                                                                                
array len : 2132 time used for old : 0.115000 s time used for new : 0.038000 s                                                                                                                
array len : 2152 time used for old : 0.116000 s time used for new : 0.038000 s                                                                                                                
array len : 2313 time used for old : 0.125000 s time used for new : 0.040000 s                                                                                                                
array len : 2404 time used for old : 0.131000 s time used for new : 0.042000 s

**Comment by pkufool** [comment]
I tested the two versions of `CreateLcpArray` using the same data, code showed in the picture below.

image

The results  said the new version would be 2.2 ~ 3.3 times faster, the logs for 100 test cases are as follows (sorted by array length)
```
array len : 516 time used for old : 0.031000 s time used for new : 0.014000 s                                                                                                                 
array len : 532 time used for old : 0.032000 s time used for new : 0.014000 s                                                                                                                 
array len : 630 time used for old : 0.037000 s time used for new : 0.016000 s                                                                                                                 
array len : 632 time used for old : 0.038000 s time used for new : 0.016000 s                                                                                                                 
array len : 774 time used for old : 0.046000 s time used for new : 0.019000 s                                                                                                                 
array len : 777 time used for old : 0.046000 s time used for new : 0.019000 s                                                                                                                 
array len : 798 time used for old : 0.046000 s time used for new : 0.019000 s                                                                                                                 
array len : 823 time used for old : 0.047000 s time used for new : 0.018000 s                                                                                                                 
array len : 826 time used for old : 0.051000 s time used for new : 0.019000 s                                                                                                                 
array len : 843 time used for old : 0.049000 s time used for new : 0.020000 s                                                                                                                 
array len : 870 time used for old : 0.053000 s time used for new : 0.022000 s                                                                                                                 
array len : 946 time used for old : 0.053000 s time used for new : 0.021000 s                                                                                                                 
array len : 957 time used for old : 0.053000 s time used for new : 0.020000 s                                                                                                                 
array len : 1040 time used for old : 0.058000 s time used for new : 0.022000 s                                                                                                                
array len : 1040 time used for old : 0.059000 s time used for new : 0.023000 s                                                                                                                
array len : 1188 time used for old : 0.068000 s time used for new : 0.026000 s                                                                                                                
array len : 1236 time used for old : 0.070000 s time used for new : 0.026000 s                                                                                                                
array len : 1429 time used for old : 0.081000 s time used for new : 0.029000 s                                                                                                                
array len : 1591 time used for old : 0.086000 s time used for new : 0.030000 s                                                                                                                
array len : 1601 time used for old : 0.089000 s time used for new : 0.031000 s                                                                                                                
array len : 1667 time used for old : 0.090000 s time used for new : 0.031000 s                                                                                                                
array len : 1719 time used for old : 0.094000 s time used for new : 0.032000 s                                                                                                                
array len : 1767 time used for old : 0.095000 s time used for new : 0.033000 s                                                                                                                
array len : 1830 time used for old : 0.099000 s time used for new : 0.034000 s                                                                                                                
array len : 1869 time used for old : 0.103000 s time used for new : 0.035000 s                                                                                                                
array len : 1945 time used for old : 0.106000 s time used for new : 0.036000 s                                                                                                                
array len : 1948 time used for old : 0.107000 s time used for new : 0.036000 s                                                                                                                
array len : 1949 time used for old : 0.108000 s time used for new : 0.040000 s                                                                                                                
array len : 2016 time used for old : 0.109000 s time used for new : 0.035000 s                                                                                                                
array len : 2034 time used for old : 0.112000 s time used for new : 0.038000 s                                                                                                                
array len : 2050 time used for old : 0.112000 s time used for new : 0.037000 s                                                                                                                
array len : 2132 time used for old : 0.115000 s time used for new : 0.038000 s                                                                                                                
array len : 2152 time used for old : 0.116000 s time used for new : 0.038000 s                                                                                                                
array len : 2313 time used for old : 0.125000 s time used for new : 0.040000 s                                                                                                                
array len : 2404 time used for old : 0.131000 s time used for new : 0.042000 s
array len : 2414 time used for old : 0.131000 s time used for new : 0.042000 s                                                                                                                
array len : 2427 time used for old : 0.134000 s time used for new : 0.044000 s                                                                                                                
array len : 2430 time used for old : 0.132000 s time used for new : 0.042000 s                                                                                                                
array len : 2451 time used for old : 0.135000 s time used for new : 0.046000 s                                                                                                                
array len : 2490 time used for old : 0.137000 s time used for new : 0.044000 s
array len : 2525 time used for old : 0.137000 s time used for new : 0.044000 s
array len : 2527 time used for old : 0.137000 s time used for new : 0.046000 s
array len : 2645 time used for old : 0.143000 s time used for new : 0.046000 s
array len : 2813 time used for old : 0.154000 s time used for new : 0.048000 s
array len : 2816 time used for old : 0.154000 s time used for new : 0.051000 s
array len : 2966 time used for old : 0.162000 s time used for new : 0.050000 s
array len : 2970 time used for old : 0.167000 s time used for new : 0.051000 s
array len : 2983 time used for old : 0.162000 s time used for new : 0.050000 s
array len : 2986 time used for old : 0.165000 s time used for new : 0.050000 s
array len : 3005 time used for old : 0.165000 s time used for new : 0.051000 s
array len : 3022 time used for old : 0.165000 s time used for new : 0.052000 s
array len : 3039 time used for old : 0.167000 s time used for new : 0.053000 s
array len : 3080 time used for old : 0.170000 s time used for new : 0.055000 s
array len : 3084 time used for old : 0.173000 s time used for new : 0.053000 s
array len : 3137 time used for old : 0.171000 s time used for new : 0.053000 s
array len : 3147 time used for old : 0.175000 s time used for new : 0.065000 s
array len : 3224 time used for old : 0.176000 s time used for new : 0.054000 s
array len : 3227 time used for old : 0.176000 s time used for new : 0.054000 s
array len : 3236 time used for old : 0.179000 s time used for new : 0.054000 s
array len : 3271 time used for old : 0.180000 s time used for new : 0.056000 s
array len : 3299 time used for old : 0.182000 s time used for new : 0.056000 s
array len : 3303 time used for old : 0.185000 s time used for new : 0.057000 s
array len : 3337 time used for old : 0.184000 s time used for new : 0.056000 s
array len : 3344 time used for old : 0.187000 s time used for new : 0.056000 s
array len : 3345 time used for old : 0.183000 s time used for new : 0.056000 s
array len : 3581 time used for old : 0.199000 s time used for new : 0.062000 s
array len : 3598 time used for old : 0.196000 s time used for new : 0.059000 s
array len : 3627 time used for old : 0.198000 s time used for new : 0.060000 s
array len : 3650 time used for old : 0.201000 s time used for new : 0.061000 s
array len : 3667 time used for old : 0.201000 s time used for new : 0.060000 s
array len : 3756 time used for old : 0.206000 s time used for new : 0.062000 s
array len : 3757 time used for old : 0.205000 s time used for new : 0.062000 s
array len : 3842 time used for old : 0.213000 s time used for new : 0.063000 s
array len : 3906 time used for old : 0.214000 s time used for new : 0.065000 s
array len : 3916 time used for old : 0.218000 s time used for new : 0.065000 s
array len : 3971 time used for old : 0.220000 s time used for new : 0.065000 s
array len : 3981 time used for old : 0.219000 s time used for new : 0.066000 s
array len : 3988 time used for old : 0.220000 s time used for new : 0.066000 s
array len : 3993 time used for old : 0.220000 s time used for new : 0.067000 s
array len : 4022 time used for old : 0.220000 s time used for new : 0.069000 s
array len : 4047 time used for old : 0.225000 s time used for new : 0.067000 s
array len : 4118 time used for old : 0.226000 s time used for new : 0.067000 s
array len : 4183 time used for old : 0.230000 s time used for new : 0.069000 s
array len : 4222 time used for old : 0.231000 s time used for new : 0.069000 s
array len : 4271 time used for old : 0.235000 s time used for new : 0.071000 s
array len : 4333 time used for old : 0.238000 s time used for new : 0.071000 s
array len : 4383 time used for old : 0.244000 s time used for new : 0.072000 s
array len : 4405 time used for old : 0.242000 s time used for new : 0.072000 s
array len : 4450 time used for old : 0.245000 s time used for new : 0.073000 s
array len : 4470 time used for old : 0.246000 s time used for new : 0.090000 s
array len : 4487 time used for old : 0.250000 s time used for new : 0.073000 s
array len : 4636 time used for old : 0.256000 s time used for new : 0.075000 s
array len : 4676 time used for old : 0.259000 s time used for new : 0.077000 s
array len : 4771 time used for old : 0.263000 s time used for new : 0.082000 s
array len : 4821 time used for old : 0.269000 s time used for new : 0.082000 s
array len : 4924 time used for old : 0.274000 s time used for new : 0.082000 s
array len : 4947 time used for old : 0.273000 s time used for new : 0.085000 s
array len : 4986 time used for old : 0.278000 s time used for new : 0.083000 s
array len : 4989 time used for old : 0.276000 s time used for new : 0.083000 s
array len : 4997 time used for old : 0.279000 s time used for new : 0.084000 s
```

**Comment by pkufool** [comment]
@danpovey  All testes passed. Do I need to submit the code for the benchmarking?

**Pull request merged**
