### PR TITLE
fix compilation and style issues

### PR DESCRIPTION
**Pull request by qindazhu**
All tests get passed.

### CODE REVIEW

**Comment by danpovey** [comment]
Great!
I added a few functions in that PR I merged before this.. would be great if you can test them at some point.

**Comment by qindazhu** [comment]
Sure, will do in the following PR.

Seems I need to test `GetBatches` and `GetDestStates` and implement `Append` for `Ragged<T>` (should be easy to call Stack when axis ==1?), anything else?

BTW, we need to implement class `Renumbering` as well.

**Comment by danpovey** [comment]
That sounds right.  Thanks!!

**Comment by qindazhu** [comment]
OK, will do those stuff from now. Merging this PR.

**Pull request merged**
