### PR TITLE
Wrap IntersectDevice.

### LINKED ISSUE #609: Wrap GPU intersection code
Need to modify the composition and intersection code in python, so that they also work for inputs  on GPU, if treat_epsilons_specially == false.

### PR DESCRIPTION
**Pull request by csukuangfj**
Closes #609

### CODE REVIEW

**Comment by danpovey** [comment]
Cool-- looks OK to me.
In my mind we'd be calling this from the normal intersect() if it detected that it was on GPU.  But I suppose we could just have it print a warning and have the user do this.

**Comment by csukuangfj** [comment]
>In my mind we'd be calling this from the normal intersect() if it detected that it was on GPU

 The interface of `IntersectDevice` is different from `Intersect`. `IntersectDevice` is more powerful.

**Comment by danpovey** [comment]
Oh, I see, at the C++ level, the Intersect() wrapper does call IntersectDevice().

**Comment by danpovey** [comment]
This is OK with me.

**Comment by csukuangfj** [comment]
Will merge.

**Pull request merged**
