### PR TITLE
Rmepsilon refactor

### PR DESCRIPTION
**Pull request by danpovey**

### CODE REVIEW

**Comment by danpovey** [comment]
This seems to work with snowfall.
remove_epsilons_iterative_tropical is now deprecated, you should just call remove_epsilon().
@csukuangfj can you please make that change in snowfall?

**Comment by danpovey** [comment]
.. I mean, after I merge this.

**Comment by csukuangfj** [comment]
I've just changed snowfall to use `remove_epsilon_and_add_self_loops`. It works with this pull-request provided that
you merge the master branch into your current branch.

**Comment by danpovey** [comment]
thanks.  i put a back-compatibility functionl so old snowfall should work too.

**Pull request merged**
